calpa/gatsby-starter-calpa-blog

src/components/Card/index.scss
Fixes https://github.com/calpa/blog/issues/21
=> 💧 Remove duplicated css

src/components/Sidebar/LatestPost/index.js, src/templates/blog-post.js, src/templates/page.js
=> Fix 3 Style issues in multiple files

src/components/ShareBox/index.scss
=> Fix CodeFactor errors in Sharebox index.scss

.eslintrc
Resolve #32
Added exception for css
=> add import extensions rule

src/api/graphql.js, src/api/url.js, src/components/Layout/layout.js, src/pages/tags/index.js
Resolves Issue #41 
Remove unused variables in four files
=> Issue #41: remove unused variables in four files

.czrc, package.json
=> Add commitizen

src/components/Navbar/NavItem/Dropdown/index.js, src/components/Navbar/index.js, src/pages/tags/index.js
Added button type to the following:
src\pages\tags\index.js:141
src\components\Navbar\index.js:21
src\components\Navbar\NavItem\Dropdown\index.js:6
=> Added explicit type for buttons

src/pages/tags/index.js
Fixes https://github.com/calpa/blog/issues/34
=> 🍪 Add propTypes for TagPage

src/html.js
I don't have a lot of context here so I went with some pretty generic defaults, let me know if you'd like one or more of them to be more specific
=> Added default props to html.js per issue #58

src/components/Navbar/NavItem/index.js, src/components/Navbar/NavItem/index.scss, src/components/Navbar/index.js, src/components/Navbar/index.scss, src/styles/_hover.scss
Increase the UI effect in the navbar, and trigger google analytics event when user click the navbar links.
Too low convert rate in the navbar.
See the website.
=> [Feature] Improve navbar interaction

src/components/ExternalLink/index.js, src/pages/tags/index.js
This pull request applies style fixes from code review by [CodeFactor](https://www.codefactor.io).
---
For more information, click [here](https://www.codefactor.io/repository/github/calpa/blog/issues/master?category=Style&groupId=193).
=> Apply fixes from CodeFactor

.eslintrc, data/headers.js, data/index.js, data/posts.js, gatsby-config.js, gatsby/CreatePages.js, gatsby/getMockPosts.js, gatsby/getPosts.js, gatsby/sourceNodes.js, src/pages/guestbook/index.js, src/pages/tags/index.js, src/templates/blog-post.js, src/templates/page.js
Provide a kick start demo, without bundling to any server or database.
Let user select any database with correct data structure.
Solve #40 
Yes, travis CI is passed.
=> Extract data structure from contentful CMS

src/templates/blog-post.js
Fix blog post index rendering problem
=> fix: post index

.github/CONTRIBUTING.md, README-zh-Hans.md, README-zh-Hant.md, README.md, src/components/Footer/index.js, src/components/Navbar/index.js, src/templates/blog-post.js
=> fix: repo name

PULL_REQUEST_TEMPLATE.md
For now, the pull request is so hard to write...
I open some pull request and find that some part is not useful.
=> Provide a more user friendly PR.md

README-zh-Hans.md, README-zh-Hant.md, README.md
Update features in readme.md
Solve #84
=> Docs readme 20181031

src/api/text.js, src/templates/blog-post.scss
#77(https://github.com/calpa/blog/issues/77)
=> Removed inline style

.travis.yml, package-lock.json
Fix Error: sha512-* integrity checksum failed when using sha512: wanted `sha512-A` but got `sha512-B`
Solve sha512 integrity checksum -> building error, see more in https://github.com/greenkeeperio/greenkeeper-lockfile/issues/156
=> fix: travisCI building bug

package-lock.json, package.json
Update gatsby version to 2.0.38
Solve #96
=> Greenkeeper/gatsby 2.0.38

package-lock.json, package.json
Upgrade gatsby-plugin-offline to 2.0.12
Solve #95
=> Greenkeeper/gatsby plugin offline 2.0.12

package-lock.json, package.json
=> Greenkeeper/stylelint scss 3.4.0

data/config.js, src/api/text.js, src/components/ExternalLink/index.js, src/components/Sidebar/Friend/index.js
Solve #108 
- [] I have updated the documentation accordingly.
=> fix: use noopner instead of nofollow noopener

README-zh-Hans.md, README-zh-Hant.md, README.md
Update Project name and description in README.md
=> Fix readme 20181111

src/templates/page.js
=> fix: total posts / page size = number of pages

src/api/index.js, src/templates/page.js
=> Fix pagination 20181113

README-zh-Hans.md, README-zh-Hant.md, README.md
=> docs: update fast start button

README.md
=>  Check grammar and typo mistakes in README.md

package-lock.json, package.json
=> Update GatsbyJS Dependencies

data/template/config.json, gatsby-browser.js, src/api/installFontAwesome.js, src/components/Layout/layout.js, src/components/Sidebar/index.js, src/components/Sidebar/index.scss, src/templates/blog-post.js
=> feat: add facebook fanpage link in sidebar
